### ISSUE TITLE
What happens when more than one case is satisfied by a value in `regex_factor`?

### ISSUE THREAD

**Issue by abelcastilloavant** [syberia/examples#14]
Just reading https://github.com/syberia/examples/blob/master/lib/mungebits/regex_factor.R#L4-L8

What happens when two or more of the cases are satisfied by a string?

In the example, what happens to `"barbaz"`?

**Comment by robertzk** [comment]
The explicit contract of the mungebit is that the variable should not satisfy more than one case twice. I do think you're right that we should incorporate that as an error case if it is violated.

**Comment by abelcastilloavant** [comment]
Can you check for that abstractly without a column of data? (I think "not in any easy way".)
