### ISSUE TITLE
No data for survey example

### ISSUE THREAD

**Issue by eeevayu** [syberia/examples#15]
@peterhurford There is no data for the [survey demo](https://github.com/syberia/examples/blob/master/models/dev/survey/survey.R#L14). :(

**Comment by peterhurford** [comment]
Will be resolved by https://github.com/syberia/examples/pull/16. Thanks!

**Comment by robertzk** [comment]
Thank you. @eeevayu @peterhurford

**Comment by robertzk** [comment]
@abelcastilloavant @eeevayu May you try re-running the analysis again and see if it works locally?

**Comment by eeevayu** [comment]
I tried locally but it still failed with the error 'Can not use tracked environments with stagerunners that have caching disabled (remember = FALSE)'. But when I delete the 'analyze' stage, it could run successfully. @robertzk

**Comment by robertzk** [comment]
Thanks @eeevayu! @peterhurford Would you mind taking a look if you have the time? Otherwise I'll take a shot at it.

**Comment by peterhurford** [comment]
@eeevayu Sorry for the delay but the data should be merged in now and ready. I'll test more to see if the tracked environments issue persists with analyze stage.

**Comment by robertzk** [comment]
@peterhurford Thank you for looking into this! Great to have it fixed.
